# Generated by Django 5.1.4 on 2025-03-05 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_del_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='cuisine',
        ),
    ]
